### ISSUE TITLE
Not compatible with hyper 0.11

### ISSUE THREAD

**Issue by parasyte** [Byron/yup-hyper-mock#11]
I get ``Could not find `net` in `hyper` `` when trying to use the `mock_connector!` macro with hyper 0.11.

**Comment by Byron** [comment]
Thanks for letting me know. Probably it's not too hard to fix, in case someone is interested to submit a PR.

**Comment by markcatley** [comment]
I'm keen to help out with this as yup-hyper-mock is the first step in upgrading my app to hyper 0.11.

On the surface, it looks like the issue is that the NetworkConnector and NetworkStream are no longer present in hyper, so I'd have to map that onto something else.

Has anyone done any thinking about what might need to be done? Or, where might be the best place to ask for help.

**Comment by palfrey** [comment]
I think that building a `Service` is the right way to go. https://github.com/Byron/yup-hyper-mock/pull/12 is my initial WIP work towards that, but I'm a bit stuck (see description there). Help wanted!

**Comment by Byron** [comment]
Version 3.12.0 was [just released to crates.io](https://crates.io/crates/yup-hyper-mock/3.12.0).
Thanks again to @palfrey , who single-handedly ported this crate over, leaving no character untouched :).
